### PR TITLE
rhine: compile liboverlay

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by AdFad666** [comment]
not needed due to LOCAL_SHARED_LIBRARIES .

**Comment by alviteri** [comment]
So what's wrong for me because it is not compiling for me without this ...  Please can you tell me where is the local shared libraries ????

**Comment by AdFad666** [comment]
for example

https://github.com/fxpdev/platform-hardware-qcom-display/blob/android-5.1.1_r2/msm8974/libhwcomposer/Android.mk#L9

**Comment by alviteri** [comment]
Thanks Adam ... I will close and build again but in my previous build liboverlay wasn't present

**Pull request closed without merging**
