### PR TITLE
Qpower hal: for Double tap to Wake Support

### PR DESCRIPTION
**Pull request by alviteri**

### CODE REVIEW

**Comment by alviteri** [comment]
@erikcas enable on kernel and target :+1:  and try .... thanks

**Comment by CoolDevelopment** [comment]
AFAIK wakeup-gesture-mode does not work on amami, so please test it on honami and togari

**Comment by alviteri** [comment]
Did you enable it on dtsi ??? Kernel level I mean also you need another commit ... Please see Leo PR

**Comment by CoolDevelopment** [comment]
Kernel level, but there is a newer touchscreen firmware. It was months or years ago. 
The strange is honami and togari were working

**Comment by alviteri** [comment]
OK then you have enable it and on honami and togari it is working but not on amami right .... If yes then thanks

**Pull request closed without merging**
