### PR TITLE
Bluetooth

### PR DESCRIPTION
**Pull request by humberos**

### CODE REVIEW

**Comment by alviteri** [comment]
@humberos ... checking on honami on this commit 

https://github.com/humberos/device-sony-rhine/commit/e2cbfcb1e226863fb01a9ca92828182d2e6666c9

this seems doesn't exist /sys/module/bluetooth_power/parameters/power

**Comment by humberos** [comment]
@alviteri  it's true.
I think all BT modules entries are deprecated.
Please, could you confirm that?
Also, could you confirm what UART entry is it?
I mean, to replace this:
/sys/devices/platform/msm_serial_hs.0/clock

**Comment by alviteri** [comment]
@humberos ... ok 

I can't see 
/dev/ttyHS0
/dev/ttyHS2
but I can see
ttyHSL0

I can't see
/sys/module/hci_smd/parameters/hcismd_set

I can't see your mention too
/sys/devices/platform/msm_serial_hs.0/clock

I can see
/sys/class/rfkill/rfkill0/type
/sys/class/rfkill/rfkill0/state

I can't see
/proc/bluetooth/sleep/proto

**Comment by humberos** [comment]
@alviteri 
humm!!! seems like all platforms were using the same bluetooth setup.
Ok, I will change this commit.

Please could confirm UART path?
Is it /sys/devices/f995d000.uart/clock ?

**Comment by alviteri** [comment]
@humberos 

f9928000.i2c after f9967000.i2c 

so not f995d000.uart

**Comment by humberos** [comment]
/sys/module/sco/parameters/disable_esco
^
is present?

**Comment by alviteri** [comment]
No

**Comment by humberos** [comment]
/sys/module/bluetooth/parameters/disable_esco

maybe?

**Comment by alviteri** [comment]
yes 
/sys/module/bluetooth/parameters

disable_ertm
disable_esco
enable_hs

**Comment by humberos** [comment]
updated!

**Comment by alviteri** [comment]
Now seems OK.

**Comment by alviteri** [comment]
But I can't see this too

/dev/rfcomm0

**Comment by humberos** [comment]
Oh! Thanks!
I will remove it.
Shall I remove more anyone ?

**Comment by alviteri** [comment]
Nope after that all seems OK for me

**Comment by humberos** [comment]
Thank you!
Btw, do you have an Yukon device too?
If yes, please could you check these entries?

**Pull request merged**
